
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ┌](text)\
$os\
$username\
[](bg:lavender fg:text)\
$directory\
[](bg:blue fg:lavender)\
$git_branch\
$git_status\
[](fg:blue bg:blue)\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:blue)\
$conda\
[](fg:blue )\


$time\
[](fg:peaCh )\

$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'


[os]
disabled = false
style = "bg:text fg:base"

[os.symbols]
EndeavourOS = " "
CachyOS = " "

[username]
show_always = false
style_user = "bg:text fg:crust"
style_root = "bg:text fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:lavender fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "  ~"


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $branch ](fg:crust bg:blue)]($style)'

[git_status]
style = "bg:blue"
format = '[[($all_status$ahead_behind )](fg:crust bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[kotlin]#9d7cd8
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context) ](fg:crust bg:blue)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:blue"
format = '[$symbol$environment ]($style)'
ignore_base = false


[character]
success_symbol = "[ └─](bold fg:#)[](fg:blue)"
error_symbol   = "[ └─](bold fg:#)[](fg:red)"
vimcmd_symbol  = "[❮❮ ﾒ](fg:#6fa3b1)"

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[───────────────────](fg:surface0)[](#af7e5f)[](fg:#af7e5f bg:#af7e5f)[](fg:peach bg:#af7e5f )[[ at $time  ](fg:crust bg:peach)]($style)'

[cmd_duration]
show_milliseconds = true
format = "  Done in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#d3869b"
flamingo = "#ea6962"
pink = "#d3869b"
mauve = "#d3869b"
red = "#ea6962"
maroon = "#ea6962"
peach = "#e78a4e"
yellow = "#d8a657"
green = "#a9b665"
teal = "#89b482"
sky = "#89b482"
sapphire = "#7daea3"
blue = "#7daea3"
lavender = "#d3869b"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#504945"
surface1 = "#3c3836"
surface0 = "#32302f"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"
